# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/noob212/Documents/Computer Science/Graphics"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/noob212/Documents/Computer Science/Graphics"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/noob212/Documents/Computer Science/Graphics/CMakeFiles" "/home/noob212/Documents/Computer Science/Graphics//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/noob212/Documents/Computer Science/Graphics/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named static_graphics

# Build rule for target.
static_graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 static_graphics
.PHONY : static_graphics

# fast build rule for target.
static_graphics/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/static_graphics.dir/build.make CMakeFiles/static_graphics.dir/build
.PHONY : static_graphics/fast

#=============================================================================
# Target rules for targets named dynamic_graphics

# Build rule for target.
dynamic_graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dynamic_graphics
.PHONY : dynamic_graphics

# fast build rule for target.
dynamic_graphics/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynamic_graphics.dir/build.make CMakeFiles/dynamic_graphics.dir/build
.PHONY : dynamic_graphics/fast

#=============================================================================
# Target rules for targets named graphics

# Build rule for target.
graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graphics
.PHONY : graphics

# fast build rule for target.
graphics/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/build
.PHONY : graphics/fast

src/gcl_geometry.o: src/gcl_geometry.c.o
.PHONY : src/gcl_geometry.o

# target to build an object file
src/gcl_geometry.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/static_graphics.dir/build.make CMakeFiles/static_graphics.dir/src/gcl_geometry.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynamic_graphics.dir/build.make CMakeFiles/dynamic_graphics.dir/src/gcl_geometry.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/src/gcl_geometry.c.o
.PHONY : src/gcl_geometry.c.o

src/gcl_geometry.i: src/gcl_geometry.c.i
.PHONY : src/gcl_geometry.i

# target to preprocess a source file
src/gcl_geometry.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/static_graphics.dir/build.make CMakeFiles/static_graphics.dir/src/gcl_geometry.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynamic_graphics.dir/build.make CMakeFiles/dynamic_graphics.dir/src/gcl_geometry.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/src/gcl_geometry.c.i
.PHONY : src/gcl_geometry.c.i

src/gcl_geometry.s: src/gcl_geometry.c.s
.PHONY : src/gcl_geometry.s

# target to generate assembly for a file
src/gcl_geometry.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/static_graphics.dir/build.make CMakeFiles/static_graphics.dir/src/gcl_geometry.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynamic_graphics.dir/build.make CMakeFiles/dynamic_graphics.dir/src/gcl_geometry.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/src/gcl_geometry.c.s
.PHONY : src/gcl_geometry.c.s

src/gcl_init.o: src/gcl_init.c.o
.PHONY : src/gcl_init.o

# target to build an object file
src/gcl_init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/static_graphics.dir/build.make CMakeFiles/static_graphics.dir/src/gcl_init.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynamic_graphics.dir/build.make CMakeFiles/dynamic_graphics.dir/src/gcl_init.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/src/gcl_init.c.o
.PHONY : src/gcl_init.c.o

src/gcl_init.i: src/gcl_init.c.i
.PHONY : src/gcl_init.i

# target to preprocess a source file
src/gcl_init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/static_graphics.dir/build.make CMakeFiles/static_graphics.dir/src/gcl_init.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynamic_graphics.dir/build.make CMakeFiles/dynamic_graphics.dir/src/gcl_init.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/src/gcl_init.c.i
.PHONY : src/gcl_init.c.i

src/gcl_init.s: src/gcl_init.c.s
.PHONY : src/gcl_init.s

# target to generate assembly for a file
src/gcl_init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/static_graphics.dir/build.make CMakeFiles/static_graphics.dir/src/gcl_init.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynamic_graphics.dir/build.make CMakeFiles/dynamic_graphics.dir/src/gcl_init.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/src/gcl_init.c.s
.PHONY : src/gcl_init.c.s

src/gcl_math.o: src/gcl_math.c.o
.PHONY : src/gcl_math.o

# target to build an object file
src/gcl_math.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/static_graphics.dir/build.make CMakeFiles/static_graphics.dir/src/gcl_math.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynamic_graphics.dir/build.make CMakeFiles/dynamic_graphics.dir/src/gcl_math.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/src/gcl_math.c.o
.PHONY : src/gcl_math.c.o

src/gcl_math.i: src/gcl_math.c.i
.PHONY : src/gcl_math.i

# target to preprocess a source file
src/gcl_math.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/static_graphics.dir/build.make CMakeFiles/static_graphics.dir/src/gcl_math.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynamic_graphics.dir/build.make CMakeFiles/dynamic_graphics.dir/src/gcl_math.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/src/gcl_math.c.i
.PHONY : src/gcl_math.c.i

src/gcl_math.s: src/gcl_math.c.s
.PHONY : src/gcl_math.s

# target to generate assembly for a file
src/gcl_math.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/static_graphics.dir/build.make CMakeFiles/static_graphics.dir/src/gcl_math.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dynamic_graphics.dir/build.make CMakeFiles/dynamic_graphics.dir/src/gcl_math.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/src/gcl_math.c.s
.PHONY : src/gcl_math.c.s

test.o: test.c.o
.PHONY : test.o

# target to build an object file
test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/test.c.o
.PHONY : test.c.o

test.i: test.c.i
.PHONY : test.i

# target to preprocess a source file
test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/test.c.i
.PHONY : test.c.i

test.s: test.c.s
.PHONY : test.s

# target to generate assembly for a file
test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/test.c.s
.PHONY : test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dynamic_graphics"
	@echo "... graphics"
	@echo "... static_graphics"
	@echo "... src/gcl_geometry.o"
	@echo "... src/gcl_geometry.i"
	@echo "... src/gcl_geometry.s"
	@echo "... src/gcl_init.o"
	@echo "... src/gcl_init.i"
	@echo "... src/gcl_init.s"
	@echo "... src/gcl_math.o"
	@echo "... src/gcl_math.i"
	@echo "... src/gcl_math.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

